#!/usr/bin/perl -w
###############################################################################
#	Script: mr_beautify
###############################################################################

use strict;
use warnings;
use Encode;	# part of perl
use Term::ANSIColor qw(:constants);

use FileHandle;
STDOUT->autoflush;	# make output unbuffered

while (my $line = <>) {
	if ($line =~ /^\sM\s(.*)$/) {
		printf "  %s M %s%s\n", YELLOW, $1, RESET;
	} elsif ($line =~ /^mr .*: finished \(.*\)/) {
		printf "\n%s%s%s", GREEN, $line, RESET;
	} elsif ($line =~ /^\?(.*)$/) {
		printf "  %s?%s%s\n", YELLOW, $1, RESET;
	} elsif ($line =~ /^\s*$/) {
		# skip empty lines
	} elsif ($line =~ /command failed$/) {
		printf "  %s%s%s", RED, $line, RESET;
	} elsif ($line =~ /fail/) {
		printf "%s%s%s", RED, $line, RESET;
	} elsif ($line =~ /Current branch master is up to date/) {
		printf "  %s%s%s", FAINT, $line, RESET;
	} elsif ($line =~ /Cloning into/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^UU\s/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^U\s/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^Cannot pull with rebase: You have unstaged changes./) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^Please commit or stash them/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^Pull is not possible/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^Please, fix them up/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
	} elsif ($line =~ /^as appropriate to mark resolution/) {
		printf "  %s%s%s", YELLOW, $line, RESET;
		
	} else {
		print $line;
	}
}
